// Worker entrypoint. OpenNext generates `.open-next/worker.js` with the Next.js
// `fetch` handler; we re-export it and add the `scheduled` handler for the cron
// trigger declared in wrangler.jsonc, which Cloudflare cannot route to a Next
// route on its own.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`; this
// file is excluded from tsconfig because that import only resolves after a build.
import { default as handler } from "./.open-next/worker.js";

// Typed structurally rather than via @cloudflare/workers-types, whose globals
// would otherwise be pulled into the Next app's own typecheck.
type Env = { NEXT_PUBLIC_APP_URL: string; CRON_SECRET: string };
type Ctx = { waitUntil(promise: Promise<unknown>): void };

const worker = {
  fetch: handler.fetch,

  // Calls the existing retention route in-process rather than over the network,
  // reusing its CRON_SECRET check so the endpoint has exactly one code path.
  async scheduled(_event: { cron: string; scheduledTime: number }, env: Env, ctx: Ctx) {
    const request = new Request(`${env.NEXT_PUBLIC_APP_URL}/api/cron/audit-retention`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`audit-retention cron failed: ${response.status} ${await response.text()}`);
    }
  },
};

export default worker;
